Udiskie changes and streaming script

diff --git a/Scripts/dismount b/Scripts/dismount
--- a/Scripts/dismount
+++ b/Scripts/dismount
@@ -4,8 +4,12 @@
 target=$(awk '/media\/[\^A-Z]/ {print $3}' <(mount))
 
 if [[ -n "$target" ]]; then
-    udiskie-umount "$target" &&
-    printf "%s\n" "${target##*/} unmounted…"
+    udiskie-umount -s "$target" &>/dev/null
+    if [[ $? = 0 ]]; then
+        printf "%s\n" "${target##*/} unmounted…"
+    else
+        printf "%s\n" "Unmounting failed."
+    fi
 else
     printf "%s\n" "No drive mounted…"
 fi
